### ISSUE TITLE
fixEmptyConfiguration may cause an error

### ISSUE THREAD

**Issue by guelzow** [hoogi91/charts#12]
Hi everyone.

**Version(s) affected**: 1.1.0

**Description**  
The class `Hoogi91\Charts\Controller\Wizard\TableController` tries to fix empty values with the method `fixEmptyConfiguration`.
This method gets it's `$configuration` from the `TYPO3\CMS\Backend\Controller\Wizard\TableController::getConfiguration`, and expects an array. The problem is that the method may return an object instead.

See: https://github.com/hoogi91/charts/blob/1.1.0/Classes/Controller/Wizard/TableController.php#L47
And: https://github.com/TYPO3/TYPO3.CMS/blob/v10.4.4/typo3/sysext/backend/Classes/Controller/Wizard/TableController.php#L251

**How to reproduce**  
Not sure if I can be helpful here. I'm only able to reproduce this with the `save_close_ce` extension and when save_and_close'ing one of our custom record.

But . . .
See: https://github.com/TYPO3/TYPO3.CMS/blob/v10.4.4/typo3/sysext/backend/Classes/Controller/Wizard/TableController.php#L294
Here we have the save and close action, which may (or may not) return an object instead of an array. It does not happen with all of records types.

Looks like the core devs have the save_and_close action forgotten in there.

**Possible Solution**  
Either declare `save_close_ce` incompatible, or test if you are handling an array.

Tobi

**Comment by hoogi91** [comment]
Hey @guelzow, problem should be solved with newest release [1.1.1](https://github.com/hoogi91/charts/releases/tag/1.1.1)
