### ISSUE TITLE
LibraryRegistry doesn't support DI 

### ISSUE THREAD

**Issue by dkd-friedrich** [hoogi91/charts#15]
**Version(s) affected**: 

1.1.0, TYPO3 10.4

**Description**  

To display a list of registered chart libraries in the extensions settings, `LibraryRegistry` is loading ext_localconf.php of all loaded extensions. Unfortunately by just loading the configurations via `ExtensionManagementUtility` the dependency injection (DI) is not supported and if classes used in ext_localconf.php depend on that, an `ArgumentCountError` occurs in the extension configuration module.

**How to reproduce**  

Prepare a TYPO3 10.4 installation and install charts 1.1.0 and evoweb/extender 7.x, then try to open extension configuration module.

**Possible Solution**  

Adapt required bootstrapping in `LibraryRegistry`.

**Additional context**  

Details about the exception to expect when trying to reproduce:

```
(1/1) ArgumentCountError

Too few arguments to function Evoweb\Extender\Utility\ClassLoader::__construct(), 0 passed in /var/www/html/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3481 and exactly 2 expected
```

**Comment by hoogi91** [comment]
Hey @dkd-friedrich, the problem should be resolved with release [1.1.1](https://github.com/hoogi91/charts/releases/tag/1.1.1)
