### ISSUE TITLE
Missing RenderType for all FlexFrom select fields

### ISSUE THREAD

**Issue by tobiasquadflieg** [hoogi91/charts#16]
**Version(s) affected**: 1.1.0

**Description**  
Every Position select field missing a renderType selectSingle

**How to reproduce**  
Create a new Chart CE, in the FlexForm the position select field causes `Unknown type: select, render type: select`

**Possible Solution**  
Add to every select that is a single select the renderType `<renderType>selectSingle</renderType>`

**Comment by hoogi91** [comment]
Hey @tobiasquadflieg, the problem should be resolved with release [1.1.1](https://github.com/hoogi91/charts/releases/tag/1.1.1)
