### ISSUE TITLE
Charts.js v3

### ISSUE THREAD

**Issue by saitho** [hoogi91/charts#19]
**Description**  

In April 2021 Charts.js v3 released. This extension currently uses v2 and should probably use the latest version.
Migration guide: https://www.chartjs.org/docs/latest/getting-started/v3-migration

**Comment by hoogi91** [comment]
Hey @saitho,

thanks for your request and the PR :)
Your changes are now available in https://github.com/hoogi91/charts/releases/tag/1.1.2

I will keep this issue open to consider it for next major version to update the frontend dependencies :)

**Comment by saitho** [comment]
Great, thanks!

**Comment by hoogi91** [comment]
Hey,

today I released [v2 of this extension](https://github.com/hoogi91/charts/releases/tag/2.0.0).
With that release I updated the default version of ChartJS to v3.
Additionally it's now also possible to define in extension settings which CDN Url you want to use to easily pin the used version or to upgrade onto a newer one. The pre-compiled JavaScript and the CDN can also both be disabled in the settings to inject the library by yourself. 
Currently there is no better way then pushing something like the following JS into the DOM to get the chart data into the frontend:
```
document.addEventListener('DOMContentLoaded', () => window['Hoogi91.Charts'].init());
window['Hoogi91.chartsData'] = {};
window['Hoogi91.chartsData']['chartsData123456'] = {
    labels: ["Label 1", "Label 2", "Label 3"],
    datasets: [
        {
            "background": ["rgb(255, 0, 0)", "rgb(0, 255, 0)", "rgb(0, 0, 255)"],
            "border": [],
            "data": ["Data 1-1", "Data 1-2", "Data 1-3"],
            "label": ""
        },
        {
            "background": ["rgb(255, 0, 0)", "rgb(0, 255, 0)", "rgb(0, 0, 255)"],
            "border": [],
            "data": ["Data 2-1", "Data 2-2", "Data 2-3"],
            "label": ""
        },
        {
            "background": ["rgb(255, 0, 0)", "rgb(0, 255, 0)", "rgb(0, 0, 255)"],
            "border": [],
            "data": ["Data 3-1", "Data 3-2", "Data 3-3"],
            "label": ""
        }
    ]
};
```
