### ISSUE TITLE
Plain dataset charts are missing some labels

### ISSUE THREAD

**Issue by saitho** [hoogi91/charts#29]
**Version(s) affected**: 2.0.0+

**Description**  
We're using a plain dataset record with two labels ("Label 1", "Label 2"). However only the first label is displayed in frontend.

![missing-label2](https://user-images.githubusercontent.com/7293310/164693278-0b53d431-e5a9-4a8d-9be3-691ee271ab97.png)

**How to reproduce**  

Chart Dataset:

_Labels:_
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3TableWizard>
    <numIndex index="2" type="array">
        <numIndex index="2">97</numIndex>
        <numIndex index="4">98</numIndex>
        <numIndex index="6">99</numIndex>
        <numIndex index="8">00</numIndex>
        <numIndex index="10">01</numIndex>
        <numIndex index="12">02</numIndex>
        <numIndex index="14">03</numIndex>
        <numIndex index="16">04</numIndex>
        <numIndex index="18">05</numIndex>
        <numIndex index="20">06</numIndex>
        <numIndex index="22">07</numIndex>
        <numIndex index="24">08</numIndex>
        <numIndex index="26">09</numIndex>
        <numIndex index="28">10</numIndex>
        <numIndex index="30">11</numIndex>
        <numIndex index="32">12</numIndex>
        <numIndex index="34">13</numIndex>
        <numIndex index="36">14</numIndex>
        <numIndex index="38">15</numIndex>
        <numIndex index="40">16</numIndex>
        <numIndex index="42">17</numIndex>
        <numIndex index="44">18</numIndex>
        <numIndex index="46">19</numIndex>
        <numIndex index="48">20</numIndex>
    </numIndex>
</T3TableWizard>
```

_Datasets:_
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3TableWizard>
	<numIndex index="2" type="array">
		<numIndex index="2">300</numIndex>
		<numIndex index="4">310</numIndex>
		<numIndex index="6">340</numIndex>
		<numIndex index="8">420</numIndex>
		<numIndex index="10">410</numIndex>
		<numIndex index="12">430</numIndex>
		<numIndex index="14">410</numIndex>
		<numIndex index="16">440</numIndex>
		<numIndex index="18">480</numIndex>
		<numIndex index="20">540</numIndex>
		<numIndex index="22">600</numIndex>
		<numIndex index="24">610</numIndex>
		<numIndex index="26">510</numIndex>
		<numIndex index="28">540</numIndex>
		<numIndex index="30">620</numIndex>
		<numIndex index="32">610</numIndex>
		<numIndex index="34">630</numIndex>
		<numIndex index="36">660</numIndex>
		<numIndex index="38">710</numIndex>
		<numIndex index="40">720</numIndex>
		<numIndex index="42">780</numIndex>
		<numIndex index="44">850</numIndex>
		<numIndex index="46">900</numIndex>
		<numIndex index="48">950</numIndex>
	</numIndex>
	<numIndex index="4" type="array">
		<numIndex index="2">400</numIndex>
		<numIndex index="4">410</numIndex>
		<numIndex index="6">440</numIndex>
		<numIndex index="8">520</numIndex>
		<numIndex index="10">510</numIndex>
		<numIndex index="12">530</numIndex>
		<numIndex index="14">510</numIndex>
		<numIndex index="16">540</numIndex>
		<numIndex index="18">580</numIndex>
		<numIndex index="20">640</numIndex>
		<numIndex index="22">700</numIndex>
		<numIndex index="24">710</numIndex>
		<numIndex index="26">610</numIndex>
		<numIndex index="28">640</numIndex>
		<numIndex index="30">520</numIndex>
		<numIndex index="32">510</numIndex>
		<numIndex index="34">530</numIndex>
		<numIndex index="36">560</numIndex>
		<numIndex index="38">710</numIndex>
		<numIndex index="40">620</numIndex>
		<numIndex index="42">780</numIndex>
		<numIndex index="44">950</numIndex>
		<numIndex index="46">800</numIndex>
		<numIndex index="48">850</numIndex>
	</numIndex>
</T3TableWizard>
```

_Dataset Labels:_
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3TableWizard>
	<numIndex index="2" type="array">
		<numIndex index="2">Label 1</numIndex>
		<numIndex index="4">Label 2</numIndex>
	</numIndex>
</T3TableWizard>
```

**Possible Solution**  

`Hoogi91\Charts\Domain\Model\ChartDataPlain::getDatasetsLabels` grabs the first column of `$labels`:
```php
public function getDatasetsLabels(): array
{
    // grab first column of every row as dataset labels in plain element
    $labels = $this->extractLabelList($this->datasetsLabels);
    return array_column($labels, '0') ?? [];
}
```

For the XML above `$labels` is `[['Label 1', 'Label 2']]`.
By running `array_column($labels, '0')` the method will return only `['Label 1']`

**Comment by dkd-friedrich** [comment]
Hi! I am working with @saitho on the project/problem mentioned. I was able to take a closer look at the problem today and if I understand the modifications correctly, it is an intentional change to the configuration method. If I change the label definitions and create a label per dataset as described in the documentation (see. https://github.com/hoogi91/charts/blob/develop/Documentation/Images/dataset-plain.png), the labels are shown as expected.

I think that the current form of configuration makes sense and is more intuitive than placing the data in one row. However, when updating from an older version and more than one dataset is used, the problem will occur and from my point of view it should be mentioned in the documentation as a breaking change.

**Comment by hoogi91** [comment]
Hey @saitho and @dkd-friedrich,

please have a look on latest release [2.0.6](https://github.com/hoogi91/charts/releases/tag/2.0.6) which adds a bit more logic to the dataset label method. If there is only a single row, the method now returns all column values. If there is more than one row, the existing logic will apply and only the first column values are returned. 

I think this will make it even more intuitive than currently and it's also a working fix for updating from older versions where the content was saved as a single row 😃 
I hope this also fits into your case, please let me know if not! Cheers 🍻

**Comment by dkd-friedrich** [comment]
Hi @hoogi91. Thanks for the adaptions and the information. It took quite some time, but finally we could test the new version in our project, the new version works for us and also the use of both label configurations is possible.
