### ISSUE TITLE
Missing extension options in BE 

### ISSUE THREAD

**Issue by rtoenjes** [hoogi91/charts#32]
**Version(s) affected**: 2.0.6 (and before)
TYPO3 10.4.28

**Description** 
When doing a fresh installation, the extension options in BE for legends and more are missing.

**Possible Solution** 
Changing in extension options from default apexcharts to chartjs (and back) and saving the content element again (no change needed).

**Comment by hoogi91** [comment]
Hey @rtoenjes,

thanks for your report. I finally changed this behaviour in new release version [3.0.0](https://github.com/hoogi91/charts/releases/tag/3.0.0), due to the fact that in older versions it's relatively easy to fix this issue by just updating the extension configuration once :)
