### ISSUE TITLE
Issue while loading chartjs.js file

### ISSUE THREAD

**Issue by FloB95** [hoogi91/charts#368]
**Version(s) affected**: 3

**Description**  
There is currently a bug in the `Hoogi91\Charts\DataProcessing\Charts\Library\ChartJs` class. The JavaScript file is not being loaded in TYPO3 12 due to an incorrect path. As a result, the charts are not appearing in the frontend.

**How to reproduce**  
<img width="1041" alt="image" src="https://github.com/hoogi91/charts/assets/16621676/3f819421-25f0-493b-8e72-f4175200beaa">

**Possible Solution**  
Use EXT: in path:
<img width="1045" alt="image" src="https://github.com/hoogi91/charts/assets/16621676/cb630e6b-95be-4221-a2a2-93c78db11479">

**Comment by hoogi91** [comment]
Solved with Release [3.0.1](https://github.com/hoogi91/charts/releases/tag/3.0.1)
