### ISSUE TITLE
PHP 8.3 support

### ISSUE THREAD

**Issue by saitho** [hoogi91/charts#511]
Hi @hoogi91,

PHP 8.2 will only be receiving security updates starting the next year.
We're currently looking into upgrading our projects to PHP 8.3.

This extension is currently restricted to PHP 8.1 and 8.2.
Can you allow PHP 8.3 in the dependencies, or are there known issues with that PHP version?

Kind regards
Mario

**Comment by hoogi91** [comment]
Solved with Release [3.0.1](https://github.com/hoogi91/charts/releases/tag/3.0.1)
