### ISSUE TITLE
Wrong colors rendering in FE

### ISSUE THREAD

**Issue by ikonplant** [hoogi91/charts#549]
**Version(s) affected**: 2.0.6

- TYPO3 10.4
- PHP 7.4
- hoogi91/charts 2.0.6
- hoogi91/spreadsheets 3.3.1
- Chart.js v3.9.1
- ApexCharts v3.51.0

**Description**  

If the amount of selected _Dataset Labels (single row or column)[spreadsheet_datasets_labels]_ is bigger, than amount of selected _Labels (single row or column)[spreadsheet_labels]_ , the colors in the FE are wrong. The third color of the example below should be magenta, not grey or black.

**How to reproduce**  

1. Configure colors globally, as provided below
2. Upload provided Excel to the file storage
3. Create Chart Dataset `tx_charts_domain_model_chartdata`
4. Select Labels, Datasets, Dataset Labels as provided below
5. Create CE chart, e.g. Bar Chart [chart_bar] with Chart Data[tx_charts_chartdata] created before
6. Render FE

**Additional context**  

* Excel sheet: 
[test_diagramm_daten_de.xlsx](https://github.com/user-attachments/files/16424960/test_diagramm_daten_de.xlsx)

* Globally configured colors:
```
TCAdefaults {
    tx_charts_domain_model_chartdata {
        border_colors=#DFF2FD|#E9F1F0|#F5E5EF|#FDEFE1
        background_colors=#006699|#007E71|#BA4682|#E18922
    }
}
```

* DB `tx_charts_domain_model_chartdata`:
```
uid,pid,l10n_parent,spreadsheet_labels,spreadsheet_datasets,spreadsheet_datasets_labels,background_colors,border_colors
80,99484,0,spreadsheet://662674?index=0&range=B1:C1&direction=horizontal,spreadsheet://662674?index=0&range=B2:C4&direction=horizontal,spreadsheet://662674?index=0&range=A2:A4&direction=vertical,#006699|#007E71|#BA4682|#E18922,#DFF2FD|#E9F1F0|#F5E5EF|#FDEFE1
```

* chartsData80 provided via PHP to the JS:
`window['Hoogi91.chartsData']['chartsData80'] = {labels: ["weiblich","m\u00e4nnlich"], datasets: [{"background":["#006699","#007E71"],"border":["#DFF2FD","#E9F1F0"],"data":[2500,3000],"label":"Bachelor"},{"background":["#006699","#007E71"],"border":["#DFF2FD","#E9F1F0"],"data":[1500,2000],"label":"Master"},{"background":["#006699","#007E71"],"border":["#DFF2FD","#E9F1F0"],"data":[100,200],"label":"Doktorat"}]};
`

* Working multicolored examples by ApexCharts and Chart.js:
  * https://apexcharts.com/javascript-chart-demos/column-charts/basic/
  * https://www.chartjs.org/docs/latest/samples/bar/stacked.html
  * https://www.chartjs.org/docs/latest/samples/bar/stacked-groups.html

* Screenshot `tx_charts_domain_model_chartdata` BE:
![charts_BE](https://github.com/user-attachments/assets/a8198754-4c7d-49cd-9e5c-e8c5cf3ef04a)

* Screenshot result FE:
![charts_FE](https://github.com/user-attachments/assets/d786da45-5b26-40dc-a8fb-056f4d835587)

**Comment by hoogi91** [comment]
Hey @ikonplant,

thanks for the detailed report. I had already a look into it and it seems to be a small bugfix :) 
If there is enough time I will try to create a bugfix release this weekend :)

**Comment by hoogi91** [comment]
Hey @ikonplant,

this issue should be solved with either charts version [2.0.7](https://github.com/hoogi91/charts/releases/tag/2.0.7) or [3.0.2](https://github.com/hoogi91/charts/releases/tag/3.0.2)
Can you test this and write me some feedback?
Thanks

**Comment by ikonplant** [comment]
Hi @hoogi91 !
Thank you!
I will have a look at it tomorrow and give you my feedback.

**Comment by hoogi91** [comment]
Okay I will try to solve both ways in #560
