### ISSUE TITLE
Can't bring Extension to work - no Output is shown. Probably some requirement is missing, but isn't listed anywhere

### ISSUE THREAD

**Issue by JenHa** [hoogi91/charts#6]
**Version(s) affected**: 
charts: 1.0.4
typo3: 9.5.*

**Description**  
I can't bring the Extension to output anything. I tried without Spreadsheet and with Spreadsheet. I used Charts.js for FE output, but didn't work with Chartist either. Output is Empty. 
If I use Spreadsheet and try to craete some data (by opening the Table wizard) only the checkbox "Small fields" is shown. 
![image](https://user-images.githubusercontent.com/24609663/70134966-6344b800-1689-11ea-85cc-b5ac36e5e62e.png)

Also I saw some attributes of the content element, which I didn't had a form field for: 
![image](https://user-images.githubusercontent.com/24609663/70135214-e5cd7780-1689-11ea-968a-4ed934465fbf.png)
I don't have a field for Cutout Percentage and Legend. 

I tried it with a clean typo3 9.5.11 instance. 

**How to reproduce**  
Require charts and spreadsheet with composer under TYPO3 9.5.* (I tried 9.5.11 and 9.5.9). Create a new chart dataset in the list module, click on the table symbol. --> empty form wizard should show. 
create a new chart content element and add a chart dataset, open FE --> nothing should be shown

I assume I'm missing some requirement, but it isn't listed anywhere. 
Anyone an idea what causes the problem? 

Thanks in advance

**Comment by hoogi91** [comment]
Hey @JenHa,

thx for the report. The missing table wizard is indeed a bug which comes from the TYPO3 "TYPO3\CMS\Backend\Controller\Wizard\TableController". The old implementation of the method "getConfigCode" has been moved to "getConfiguration". On an empty/non-configured setup the text fields have no content and the wizard will not show anything. To fix that I had an override "Hoogi91\Charts\Controller\Wizard\TableController" but that actually only affects the old "getConfigCode" method call. So I will fix this later and push a new version to the TER.

The missing attributes you mentioned are not reproducable for me. They should appear under the "Chart Data" section as "Plugin Options" based on a flexform. So maybe check that no user/group settings or an additional TCA override is hiding the pi_flexform field from view. On a fresh install i can see them :)

If your elements are not shown in FE please consider that you add the TypoScript to your (root) template section e.g.:
![grafik](https://user-images.githubusercontent.com/13648604/70185769-bac74000-16ea-11ea-89d6-cb8562d5ebeb.png)

Best Regards

**Comment by JenHa** [comment]
Thanks for the quick response @hoogi91! 
I found the problems. The missing fields were a ddev caching problem. 
The missing output was a problem with the data. I tried without a spreadsheet, but didn't have an example how the data has to be structured. Don't know yet, too. But it worked with using a spreadsheet. 

A hint in the FE if the data is not correct would be great. An maybe some more documentation how the data structure has to be (with and without using a spreadsheet) and what configuration possibibilities in general you have and how they affect the output. 

Except for that: Great extension! And thanks a lot for the quick help.

**Comment by hoogi91** [comment]
> The missing output was a problem with the data. I tried without a spreadsheet, but didn't have an example how the data has to be structured. Don't know yet, too

If the table wizard is shown it's simply filling the fields and an XML structure is afterwards being saved in the fields.

And you are right that the documentation is not that informative at the moment. I will improve that part with the new version for TYPO3 v10 (and maybe v9 too).

If you want to contribute don't hesitate to create a new issue or pull request to document the missing configuration possibilites and possible issues when using the extension :)
