### ISSUE TITLE
Limit the width of the legend texts

### ISSUE THREAD

**Issue by JimHolman1199** [hoogi91/charts#8]
Hi, 
As you can see, one of the labels is very long, which makes the chart unusable.
I would like to have a way to set the maximum size of the legend, probably in pixels or have only 1 column of labels
![image007_050220_124451_PM](https://user-images.githubusercontent.com/46226026/81052482-2bf26580-8ecc-11ea-95dd-cd660ba49fee.png)

**Comment by hoogi91** [comment]
Hey @JimHolman1199,

the image is quite small... Could you please add a bigger image that explains your issue? (I can't see what is label and what is chart - and even the label text is not clear)

Which chart library are you using? ChartJS or Chartist?

Thanks in advance :)
